### ISSUE TITLE
group all stdlib imports together

### ISSUE THREAD

**Issue by ewgRa** [ewgRa/gocsfixer#3]
```
import (
	"os"
	"strconv"

	"path"
```

must be 

```
import (
	"os"
	"strconv"
	"path"
```

Inpired by https://github.com/elastic/beats/pull/6641#discussion_r177160547

**Comment by ewgRa** [comment]
closed by #8

**Comment by Quasilyte** [comment]
Doesn't `goimports` already do that?

**Comment by ewgRa** [comment]
@Quasilyte and yes and no 

`package main

import (
    "os"
)

import (
    "fmt"
)

import "strings"

func main() {
	fmt.Println(strings.Split("a", "aa"), os.Readlink("b"))
}`

Will be not changed by goimports. Idea is that such code must looks like:

`package main

import (
    "fmt"
    "os"
    "strings"
)

func main() {
	fmt.Println(strings.Split("a", "aa"), os.Readlink("b"))
}`

**Comment by ewgRa** [comment]
@Quasilyte I will later check goimports issues, I think it is kind of expected behavior

**Comment by ewgRa** [comment]
@Quasilyte can't find any already created similar issue, create one https://github.com/golang/go/issues/26795, will see is it a feature or a bug

**Comment by Quasilyte** [comment]
@ewgRa, nice! Thanks for doing it!
